// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg43oxd1pPAADQgjzTlZ4u-UlZZcSSNXM',
    appId: '1:579945944371:web:406ad11754580375ca1a46',
    messagingSenderId: '579945944371',
    projectId: 'whoami-4b511',
    authDomain: 'whoami-4b511.firebaseapp.com',
    storageBucket: 'whoami-4b511.appspot.com',
    measurementId: 'G-2FV2HV43PJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJq7z2v2qVzLWcuEJvjDBBjnndnoffUhQ',
    appId: '1:579945944371:android:c4e7c91c4b1d6cd2ca1a46',
    messagingSenderId: '579945944371',
    projectId: 'whoami-4b511',
    storageBucket: 'whoami-4b511.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI-gqcrKRBX8IStIUsaIi2Ggrg4fynb5M',
    appId: '1:579945944371:ios:1d6ad1834df35ab2ca1a46',
    messagingSenderId: '579945944371',
    projectId: 'whoami-4b511',
    storageBucket: 'whoami-4b511.appspot.com',
    iosClientId: '579945944371-0u7709jbkg7eju2293p3igjggbs1dl9p.apps.googleusercontent.com',
    iosBundleId: 'com.example.whoami',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI-gqcrKRBX8IStIUsaIi2Ggrg4fynb5M',
    appId: '1:579945944371:ios:1d6ad1834df35ab2ca1a46',
    messagingSenderId: '579945944371',
    projectId: 'whoami-4b511',
    storageBucket: 'whoami-4b511.appspot.com',
    iosClientId: '579945944371-0u7709jbkg7eju2293p3igjggbs1dl9p.apps.googleusercontent.com',
    iosBundleId: 'com.example.whoami',
  );
}
